[package]
name = "basalt"
version = "0.1.0"
edition = "2021"

[dependencies]
erupt = "0.20"
vk-mem-erupt = "0.2.3"
cgmath = "*"
tobj = "*"
structopt = "*"
first-person-camera = { git = "https://github.com/Blugatroff/first-person-camera.git" }
image = "*"
reflection = { path = "../reflection" }
egui = "*"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.sdl2]
version = "*"
features = ["raw-window-handle"]

