[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", rev = "27cd1fd67c811e06b9d997a77bb6089a1b65070d" }
basalt = { path = "../basalt/" }
egui = "0.16.1"
cgmath = "0.18"
shaders = { path = "../shaders" }
slab = "0.4"
