[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = { workspace = true }
bytemuck = { workspace = true }
basalt = { path = "../basalt/" }
gui = { path = "../gui" }
log = "0.4"
pretty_env_logger = "0.4"
puffin_egui = "0.22.0"
sdl2 = { workspace = true }

