[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "extract_structs"
path = "./src/main.rs"

[dependencies]
spirq = { git = "https://github.com/PENGUINLIONG/spirq-rs" }

